### ISSUE TITLE
Archlinux

### ISSUE THREAD

**Issue by drozzy** [chrisdone/freenect#2]
installed libfreenect-git:
https://aur.archlinux.org/packages.php?ID=43763

When doing "cabal install freenect" getting the error:
- Missing (or bad) header file: libfreenect.h
  This problem can usually be solved by installing the system package that
  provides this library (you may need the "-dev" version). If the library is
  already installed but in a non-standard location then you can use the flags
  --extra-include-dirs= and --extra-lib-dirs= to specify where it is.
  If the header file does exist, it may contain errors that are caught by the C
  compiler at the preprocessing stage. In this case you can re-run configure
  with the verbosity flag -v3 to see the error messages.
  cabal: Error: some packages failed to install:
  freenect-1.0.2 failed during the configure step. The exception was:
  ExitFailure 1

**Comment by TomMD** [comment]
I know this is old but... the package now uses pkg-config (I assume that's a recent cabal feature) and this ticket should be closed.
